### ISSUE TITLE
Tinybase not compatible with metro in react-native

### ISSUE THREAD

**Issue by kastriotkastrati** [tinyplex/tinybase#17] opened 2022-04-14 16:54 UTC
### Describe the bug

Hello, I'm trying to use tinybase for a project with react-native and I keep getting this error:

```
While trying to resolve module `tinybase` from file `---path---\App.tsx`, the package `--path--\node_modules\tinybase\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`--path---\node_modules\tinybase\index`. Indeed, none of these files exist.:.....
```

In my opinion, looks like metro has issues with the way the package is exported in package.json and cannot resolve the correct path.

### Your Example Website or App

React native is not an option in stackblitz

### Steps to Reproduce the Bug or Issue

1. Initialize a react native app
2. Install tinybase
3. Import and interact with tinybase

### Expected behavior

I would expect tinybase to work similar to how it does in a react or next app, with webpack.

### Platform

- OS: [macOS, Windows, Linux]
- Browser: [Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by jamesgpearce** [comment] 2022-04-15 03:41
Alright, this is a good one! I will take a look.

**Comment by jamesgpearce** [comment] 2022-04-15 05:30
I think this is caused by TinyBase using the `exports` field, not supported by Metro as per https://github.com/facebook/metro/issues/670 - I'm looking at workarounds.

**Comment by jamesgpearce** [comment] 2022-04-15 07:10
OK, fixed. Please update to v1.3.2. This adds a `'react-native'` field to `package.json` that allows Metro to find the file directly (since it doesn't currently support `exports`).

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/90942/163535608-cf251e14-d9be-4992-b4d7-68cddd4a7c62.png">

The `ui-react` library works too! - because it doesn't rely on the HTML DOM. But Note that until Metro fixes https://github.com/facebook/metro/issues/670 you will still have to be slightly creative and reference it explicitly from the lib folder directly:

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/90942/163536583-4f091360-0af2-4078-9705-094728e5af02.png">

Have fun and let me know how it goes!

**Comment by jamesgpearce** [comment] 2022-04-15 07:16
Fixed in https://github.com/tinyplex/tinybase/releases/tag/v1.3.2

**Closed by jamesgpearce** 2022-04-15 07:16 UTC
Labels: bug

**Comment by kastriotkastrati** [comment] 2022-04-15 09:44
Hello. While I was thinking of the architecture of the app and tinybase's position in it, I was wondering if the ui-react library would work as well, it's good to have the confirmation. 
I will be using it through explicit reference until metro fixes the issue.
Thank you for the fix.

**Comment by jamesgpearce** [comment] 2022-05-02 19:22
@kastriotkastrati how is your experience going so far?

**Comment by kastriotkastrati** [comment] 2022-05-03 15:13
@jamesgpearce 
Hello, It's going really well. Typescript throws me errors whenever I import something from 'lib/ui-react' since tinybase.d.ts does not export ui-react and that's where the imports are looking for the types. I don't know if there's something wrong with my ts configuration or whether this is expected (as you know there's a perfectly fine ui-react types file wherefrom I would have rather gotten the types). To solve my issues, I've either added @ts-ignore on the imports or primarily used other means of recreating the behavior of ui-react. I'm also obviously using a custom persister to accommodate for react-native. I've been making some helper functions to serve me somewhat like a mini-ORM, which I'm curious to know whether you think they're something that tinybase should have.
